services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - PHP_INI_DIR=/usr/local/etc/php
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - db
    networks:
      - vide-grenier-dev-network

  db:
    image: mysql:8.0
    container_name: dev-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - vide-grenier-dev-network

volumes:
  mysql_data_dev:

networks:
  vide-grenier-dev-network:
    driver: bridge
