services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dev-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: videgrenierenligne
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
